#!/bin/bash

# Vercel Deployment Quick Fix Script
# This shows you exactly what to do in Vercel dashboard

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                 VERCEL DEPLOYMENT FIX                          ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "🔍 Problem: 401 errors on deployment"
echo "💡 Cause: Frontend calling localhost instead of /api"
echo "🔧 Solution: Add NEXT_PUBLIC_API_URL to Vercel"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "STEP 1: Go to Vercel Dashboard"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Visit: https://vercel.com/jenks18s-projects/chatbot/settings/environment-variables"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "STEP 2: Add These Environment Variables"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "For EACH variable below:"
echo "  1. Click 'Add New' button"
echo "  2. Enter the Name (left side)"
echo "  3. Enter the Value (right side)"
echo "  4. Check ALL THREE: Production, Preview, Development"
echo "  5. Click 'Save'"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚨 CRITICAL (fixes API calls):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Name:  NEXT_PUBLIC_API_URL"
echo "Value: /api"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔑 Backend (required for API):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Name:  DEEPSEEK_API_KEY"
echo "Value: sk-052da17567ab438bb0ea6e80b346a85d"
echo ""
echo "Name:  DEEPSEEK_MODEL"
echo "Value: deepseek-chat"
echo ""
echo "Name:  DATABASE_URL"
echo "Value: postgresql://postgres.zzeycmksnujfdvasxoti:kMOFPkWLvHmRWATc@aws-0-us-west-1.pooler.supabase.com:6543/postgres"
echo ""
echo "Name:  OPENFDA_API_KEY"
echo "Value: rH2feOTgRtT4WRuooKmDqiHlKuDqmhhJK6GqTeAb"
echo ""
echo "Name:  NCBI_API_KEY"
echo "Value: 5141dbd81188ce3fc0547dbcf18a3fbe9209"
echo ""
echo "Name:  API_CACHE_DURATION_DAYS"
echo "Value: 30"
echo ""
echo "Name:  ENABLE_API_CACHING"
echo "Value: true"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📦 Supabase (optional - not currently used):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Name:  NEXT_PUBLIC_SUPABASE_URL"
echo "Value: https://zzeycmksnujfdvasxoti.supabase.co"
echo ""
echo "Name:  NEXT_PUBLIC_SUPABASE_ANON_KEY"
echo "Value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6ZXljbWtzbnVqZmR2YXN4b3RpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIyODUxMTYsImV4cCI6MjA3Nzg2MTExNn0.gX37n0KQK9__8oea55JA1JP-JJhF2wUG18jIeaV81oM"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "STEP 3: Redeploy"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "1. Go to Deployments tab"
echo "2. Click latest deployment"
echo "3. Click three dots (...) menu"
echo "4. Click 'Redeploy'"
echo "5. Wait 2-3 minutes"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "STEP 4: Test"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Visit your app and try asking: 'Tell me about aspirin'"
echo ""
echo "Check browser console (F12) for errors"
echo ""

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  Copy-Paste These Variables Into Vercel Dashboard             ║"
echo "║  Make sure to check ALL environments (Prod, Preview, Dev)     ║"
echo "╚════════════════════════════════════════════════════════════════╝"
